#conexión a la BD
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true